### ISSUE TITLE
Fix multiple building type tags

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#101]
![screen shot 2016-07-18 at 15 26 08](https://cloud.githubusercontent.com/assets/353700/16911433/0a882008-4cfc-11e6-84f1-a0dab269172a.png)

This happened in the initial days of importing when we don't have the combine LA building plugin in JOSM.

- [x] Extract all building with multiple tags with overpass.
- [ ] Fix tags.

**Comment by ramyaragupathy** [comment]
Issue|Query
-----|------
building with `;` in the value|http://overpass-turbo.eu/s/hqg

cc @maning

**Comment by maning** [comment]
Thanks @ramyaragupathy lets keep this ticket open and do another pass after the import is done.

**Comment by maning** [comment]
This is done.  All imported buildings have only one building value. 
Thanks @ramyaragupathy !
Closing.
