### ISSUE TITLE
Update TM to latest master to send a thank you note to all contributors

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#103]
In reference to https://github.com/osmlab/labuildings/issues/99, we need to send a thank you note to all contributors.  I checked the [users list](http://labuildingsimport.com/users) and removed duplicate account.  We have 109 user to say thanks! Full list here: https://gist.github.com/anonymous/cd0b738f11d3ce4099af1abfdeeb10b7

Sending 109 message is tedious, but there is [a new feature  to message all users](https://github.com/hotosm/osm-tasking-manager2/pull/768)  available in the TM master branch that was merged last May.  We should update our branch to use this feature.

@batpad

**Comment by jschleuss** [comment]
I've also been exploring possibly creating a python script to message multiple users through the website. It's such a pain and it really stifles community organizing.

**Comment by jschleuss** [comment]
Have you sent this yet? If not, it may be worth adding a note to future meetups (which we may be able to schedule by Friday).

**Comment by batpad** [comment]
Hey - sorry for the late response on this - I was traveling / on vacation.

I'm a bit concerned with having to setup and manage a mail server configuration on our TM instance - avoiding going into spam, things like that. If we can just generate a list of email addresses (I can help with providing this dump or so) and email them manually, that would be preferable, and also, it seems to me, probably more reliable -- but if it seems like it would be really valuable to have this functionality within the TM instance, I can see what it would take to both update our instance (probably easy) and setup a reliable mail server configuration that does not get sent to spam, etc. (probably not so easy).

**Comment by jschleuss** [comment]
@batpad yeah that sounds like a pain. 

I could start work on a python mechanize script that could log into openstreetmap.org and send messages to users. That may be easier. I've also been looking for a way to email local contributors, so I'll probably do it anyway.

**Comment by jschleuss** [comment]
Hey gang. I've completed a script to automate sending of messages through OSM. It has to log into OSM so it'll send as my username. Please let me know what we should do to change the thank you message to users. https://docs.google.com/document/d/1HohXxbUGJ23N0bTLC0UYBvfPH9roFtPuqJ09dKnEK2k/edit?usp=sharing

**Comment by jschleuss** [comment]
I sent thank you's this morning.

**Comment by jschleuss** [comment]
I spoke too soon. Got rate limited. 
![screen shot 2016-08-29 at 11 20 12 am](https://cloud.githubusercontent.com/assets/695934/18062231/d03c8fce-6dda-11e6-9ff5-510feb1f0563.png)

**Comment by jschleuss** [comment]
Done.
