### ISSUE TITLE
Fix split buildings

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#104]
LA City data was split to the parcel boundaries resulting to small polygons that should be part of the larger building  (see: [#71](https://github.com/osmlab/labuildings/issues/71)). We fix this during the import by using the [Auto-tools plugin](https://github.com/mapbox/auto-tools) in JOSM but there are instances (prior to using Auto-tools) when this wasn't fixed.

We ran a [detection for split buildings by analyzing size and shapes](https://github.com/mapbox/la-split-buildings/) of buildings using OSM-QA-tiles, turf and tilereduce.  Basic steps below:
- Filter buildings that has `lacounty:bld_id` tag.
- Find all adjacent polygons (sharing at least one edge).
- Compute area, perimeter and shape factor: 

| Properties | Description |
| --- | --- |
| _area | Area of the polygon `(meter^2)` |
| _perimeter | Perimeter `(meter)` |
| _shape | Shape factor. Circles - approach a value of 100.00, squares 78.00, thin thread-like object have the lowest shape factor approaching 0. `(4 * PI * Area) / (Perimeter^2)` |

The general idea is that **small (_area) buildings are more compact (circles and squares) while large buildings are complex and wiggly**.  The reverse should be invalid buildings.

![screen shot 2016-08-04 at 15 07 21](https://cloud.githubusercontent.com/assets/353700/17398720/c5a1c5b2-5a5b-11e6-9a73-6c56af1cf29a.png)

After several trials, we came up with an acceptable [thresholds for split buildings](https://github.com/mapbox/la-split-buildings/blob/master/map.js#L82).

```
return (p.properties._area <= 13 && p.properties._shape <= 76) ||
    (p.properties._area > 13 && p.properties._area <= 30 && p.properties._shape <= 52) ||
(p.properties._area > 30 && p.properties._area < 150 && p.properties._shape <= 17);
```

**Trial Results**

A for ~800 samples have the following results:

| Category | N | % |
| --- | --- | --- |
| 👍 (valid detection) | 661 | 81.60 |
| 👎  (invalid detection) | 147 | 18.15 |
| `¯\_(ツ)_/¯` (Don't know) | 2 | 0.25 |

**Valid detection**

![valid_small_splits](https://cloud.githubusercontent.com/assets/353700/17398590/33931306-5a5b-11e6-9817-120a3fe2bc9a.png)

![valid_large_split](https://cloud.githubusercontent.com/assets/353700/17398594/33987b66-5a5b-11e6-97d5-b0e3f2c9afbe.png)<br>_Thin/narrow rectangles_

![valid_traingles](https://cloud.githubusercontent.com/assets/353700/17398702/a7d7c400-5a5b-11e6-938a-879b5b20a4f6.png)<br>_Triangles_ 

![valid_diagonal](https://cloud.githubusercontent.com/assets/353700/17398596/33ca69a0-5a5b-11e6-883a-c3c86df8188d.png)<br>_Diagonal cuts_

**Invalid detection**

![thin_roofs_on_catwalks](https://cloud.githubusercontent.com/assets/353700/17398592/3395c4ac-5a5b-11e6-9285-b63447891ded.png)<br>_Roofs that connect other building_

![invalid_small_touching](https://cloud.githubusercontent.com/assets/353700/17398591/33940a22-5a5b-11e6-9638-b4a7a13a0dc9.png)<br>_Small buildings the slightly touches another building_

![invalid_apartments](https://cloud.githubusercontent.com/assets/353700/17398593/3396684e-5a5b-11e6-9f1b-2ee8119a4228.png)<br>
_Small square building that connects two apartment building complexes_

These are just initial results and we can tweak the thresholds as we continue.  I think the ~81% valid detection is good enough for the community to review and fix. 

Dump of split buildings **[here](https://github.com/osmlab/labuildings/blob/master/cleanup/split-buildings_2016-08-04.geojson) (~4k buildings)**.   
## Next actions
- [x] Prepare maproulette task. @jschleuss 
- [x] Announce the task to community for fixing. @jschleuss 
- [ ] Review thresholds based on the initial run and create another data dump for another fixing task if necessary. @maning

**Comment by jschleuss** [comment]
Here's the MapRoulette challenge:
http://maproulette.org/map/419

I think it's easier to edit the data in JOSM (if you allow remote control).

**Comment by maning** [comment]
Tested the maproulette task, some observations:

1. Its hard to see the error at z19 ([ticket](https://github.com/osmlab/maproulette/issues/373)).
2. After loading in JOSM, its hard to see which of the buildings was identified as an error.  Can we configure the task to select the way when loaded in JOSM?  In the GeoJSON, the way id is in the `@id` property.  AFAIK, this [is possible](https://github.com/osmlab/maproulette/commit/10f6e57c11bbd27c3958f0e41af8c082114f9ac1).
3. Using iD, we cannot do what our JOSM plugin does for merging tags with [Auto-tools](https://github.com/mapbox/auto-tools). Is this OK for the user to decide which tag to maintain?

**Comment by maning** [comment]
Posted a diary for the community to help in fixing: http://www.openstreetmap.org/user/manings/diary/39230

Current metrics as of today, let's watch if this improves after a week.

![screen shot 2016-08-09 at 15 48 42](https://cloud.githubusercontent.com/assets/353700/17513119/c8e70016-5e48-11e6-8e5e-677ad14b4f1d.png)

**Comment by maning** [comment]
@jschleuss @cityhubla Let's share this maproulette project to MaptimeLA.

**Comment by jschleuss** [comment]
Yep! [Meetup this Thursday](http://www.meetup.com/MaptimeLA/events/233592014/) will promote fixing split buildings.

**Comment by maning** [comment]
Lol! Just saw that this was done.
![screen shot 2019-02-25 at 17 25 00](https://user-images.githubusercontent.com/353700/53343860-63f23600-3922-11e9-820c-31756f1a239b.png)

72% positive detection rate is not so bad.
