### ISSUE TITLE
New OSM API to limit upload to 10k changes

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#106]
A new API upload limit will happen soon, see: https://github.com/openstreetmap/openstreetmap-website/pull/1259

We have blocks that has >10K changes and we need to find a way to either:
1. subdivide the big blocks, or,
2. make it explicit in the importing guide how to fix this via JOSM upload dialog, see: https://josm.openstreetmap.de/wiki/Help/Action/Upload#ChangesetFull

**Comment by pnorman** [comment]
Uploading changesets that large is a bad practice because you have to do it in chunks and you can end up messing up data by leaving a bunch of stray nodes if you get an interrupted connection.

**Comment by maning** [comment]
Thanks @pnorman, I'm leaning towards sub-dividing the blocks.  Will do this in the data chunking step.

**Comment by maning** [comment]
JOSM already splits the upload into several changesets when it reached the API limit.  Closing.
