### ISSUE TITLE
Contact LA City to see if we can get newer data

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#11]
I was thinking that since the City of Los Angeles has a more active Open Data initiative than the county does, maybe we could get access to the newer building footprints and/or addresses for the city only? Even if we still had to use older data for the rest of the county, this would be a huge improvement. @cityhubla, remind me, have we discussed this already?

**Comment by cityhubla** [comment]
We last talked about reaching out to the city to promote the effort to gain interest. The new dataset is part of the collaborative acquisition program called LARIAC. We could encourage LA City to push their building footprint to <a href="data.lacity.org">data.lacity.org</a> by highlighting the efforts of other cities, (SF, NY, CHI) who have their footprints accessible online and the opportunities they have created. LA could further provide in the words of Mayor Eric Garcetti, "a vast array of useful information to improve life in our city." I think a letter of request furthered by a concerted effort on the part of the OSM community and interested parties can encourage the city to add it, this short of requesting the data by way of the CPRA, (California Public Records Act).

**Comment by cityhubla** [comment]
The city open data has a request form, we can try sending it there, I'll craft the message and run it by you, @almccon

**Comment by cityhubla** [comment]
@almccon, I made a draft to request the data from DataLA, if you want to take a look, [Draft](https://docs.google.com/document/d/1C-lPnPJnYT07H70iR_wlsvKhY5MsW0yj8Ly_Bz7Ha5Q/edit?usp=sharing). I'm crafting it to bring excitement to the effort and get some contributors. I'm piecing it from these collaborative efforts, [New York City and OpenStreetMap Collaborating Through Open Data](https://www.mapbox.com/blog/nyc-and-openstreetmap-cooperating-through-open-data/). This effort with the city can include address points but maybe have something where lacity can detect changes in OSM to drive updates to their public datasets, like the [changewithin tool](https://github.com/osmlab/changewithin). We can use this language to spread the word.

**Comment by cityhubla** [comment]
@LearningNerd should join in here to bring in support from the academic crowd.

**Comment by LearningNerd** [comment]
@cityhubla Very interesting! I'll share with my team. Our focus isn't on map data right now but we are interested in more examples of how open data initiatives are developing in the cities of LA County.

**Comment by almccon** [comment]
Thanks, @cityhubla, that's great! Can you enable commenting on that document? Right now it's in read only mode.

I'd also like to loop in @talllguy for his experience in Baltimore. We can point to this article http://technical.ly/baltimore/2015/01/21/elliott-plack-putting-baltimore-openstreetmap-help-out/ to show the nice publicity that DataLA could get by sharing their data.

**Comment by talllguy** [comment]
Thanks for the mention @almccon. I think that it was good to get some press about the import--I heard from a few non-OSM people about the article, "Hey I read this article about you..." types of things. Therefore, in my experience I think that promotion via the media is especially valuable for these kinds of things because it made Baltimore City look good (and it often does not look good), and gave some exposure to OSM.

To prepare I did a little hangout with the OSM.us board to prep for the interview, to make sure I hit some key aspects of the OSM project.

Anyway, regarding getting new data and open data, I think you could show the Baltimore City import, which is nearing completion, the Baltimore County import, or the NYC import as a beacon of how government data can make for an excellent map with a lot of valuable information. For the city of LA, I would see if there is a Chief Data Officer, or a senior GIS person that is open data friendly, to try and get at the latest data. In both of the imports I worked on, the permission didn't have to come all the way from the top, so finding an advocate in the department that dealt with this kind of data was critical.

Let me know if you need more elaboration.

**Comment by cityhubla** [comment]
@almccon, it should be editable now, and thanks @LearningNerd, having other LA county cities be aware of OSM can promote the benefits of opendata. And awesome tips, @talllguy, LA does have a Chief Data Officer and a Chief Innovation & Technology Officer we can reach out to.

**Comment by almccon** [comment]
@cityhubla I'm adding our names and affiliations (please add your own) to the end, to personalize it and add credibility. I got Jon Christensen, who is a UCLA professor and a Stamen partner, to sign too, if we think that's helpful. He's very good at diplomacy and he'd love to help us build contacts with city or county government in any way he can. Who else would be useful to have sign on? Any other allies we have who also represent LA-area entities? Maybe @palewire?

**Comment by cityhubla** [comment]
@almccon Awesome, I'm getting approval for my affiliation, I'm trying to get backing from my office. I also reached out to @jschleuss from the LATimes for their thoughts. 

I made some changes to the draft, but I came across this, [DataLA Policy and Playbook]{http://datala.github.io/od-policy//roadmap/}, its a breakdown of the city's efforts, more importantly there is a roadmap which has the building footprints listed, making the letter more important. The GITHUB author is the Chief Data Officer.

**Comment by almccon** [comment]
Nice find re: @datala! That's a great thing we can point at. The draft changes look good too. The letter is getting better and better.

**Comment by jschleuss** [comment]
Looks like we'll be getting L.A. City data soon. We filed a public records request and the Times will foot the small labor bill to get the shapefiles of buildings. The newest they have is from 2012. Where should I put the file once I get it?

**Comment by almccon** [comment]
Great news, @jschleuss! You can put the file wherever you like and I can modify the [Makefile](https://github.com/osmlab/labuildings/blob/master/Makefile) to download it from there. But if you need somewhere to store it, then @iandees can hook you up with s3 credentials and you can put it here `s3://data.openstreetmap.us/imports/la/chunks/`

**Comment by almccon** [comment]
@jschleuss will this include a file of address points too, or will we still need to use addresses from 2008?

**Comment by cityhubla** [comment]
Thanks @jschleuss. @almccon, if we are unable to get them, LA County updates their points weekly, [LA County Address Points](http://egis3.lacounty.gov/dataportal/2012/06/19/la-county-address-points/), we can also link to the new [2014 Assessors data](http://egis3.lacounty.gov/dataportal/2015/03/10/assessor-parcel/), for building uses, #bedrooms and units. Mind you we need to figure out a way to have contributors make sure to do some quality check on if buildings have been built after 2012.

**Comment by almccon** [comment]
Thanks @cityhubla! I hadn't checked the recentness of the address data. It looks like I had [a link for 2012 addresses](http://egis3.lacounty.gov/dataportal/wp-content/uploads/2012/06/lacounty_address_points.zip) stored in the Makefile. Looks like your URL for addresses says 2014 at the top of the page, but gives a reference date of 2012 near the bottomt of the page? Your link is a geodatabase, which is interesting. 

That's also interesting to see the parcels link. I hadn't noticed that before. Previously I was using data from a [UCLA](http://gis.ats.ucla.edu/Mapshare/) link for 2010 apparently.

**Comment by almccon** [comment]
And yup, definitely we want to make sure the manual importers check for any newer buildings. That will be one of the most important things they will have to look for. And if possible, they should try to add the correct address to any new buildings that they trace.

**Comment by jschleuss** [comment]
I'm not sure what's going to be attached to the shapefile. I asked. [Here's the response](https://dl.dropboxusercontent.com/u/1295925/PR15-11476.pdf)

**Comment by jschleuss** [comment]
@almccon @cityhubla Here are the fields we'll get from the 2012 city shapes: Code, BLD_ID, Height, Elevation, Shape_Area, Shape_Length.

I'm pretty sure we could match some of the IDs with other datasets already [released through the portal](https://data.lacity.org/browse?Data-Owner_Data-Owner=Building+and+Safety&limitTo=datasets&utf8=✓).

**Comment by jschleuss** [comment]
Alright gang. Here is the [2012 building file](http://latimes-graphics-media.s3.amazonaws.com/jon-temp/la-buildings2012.zip). I haven't done a difference analysis to see how much this differs from the LA County 2008 file. My initial check doesn't look super promising: I think this could just be an extract from the county's 2008 file. :( Also, we're limited on attributes. BLD_ID is in there, and it appears to match the county's 2008 file.

**Comment by almccon** [comment]
I did a very quick look and spotted at least one difference... near the corner of Beverly Blvd and N Robertson Blvd:
![screen shot 2015-07-31 at 5 24 28 pm](https://cloud.githubusercontent.com/assets/1212178/9019901/50142f7c-37a9-11e5-9ae8-2099873a188e.png)

**Comment by cityhubla** [comment]
@almccon, those buildings were built during the 30's and 50's, I found another one by Queens Rd and Sunset Blvd at the Sunset Strip area.
![2012to2008_comparision](https://cloud.githubusercontent.com/assets/6407796/9023427/6fad74fa-384f-11e5-8037-7686430293aa.PNG)

Seems to me that they must have added/modified the 2008 set, albeit not much. I haven't seen anything new in terms of new buildings. My reference would be the W Hotel at Hollywood and Vine. That hotel was built in 2009, the whole block hasn't been reflected in the set given by the city. It has been in the 2014 county set.

Perhaps its been named 2012 based on the very minor modifications to the 2008 set from county.

**Comment by cityhubla** [comment]
We can easily identify which buildings have been replaced with the assessors's parcel data.
![hollywood](https://cloud.githubusercontent.com/assets/6407796/9023487/4d69e2a4-3852-11e5-84b4-143ecf202514.PNG)

this is both the 2008 buildings with the 2014 parcels, I styled the parcels with buildings built after 2008 in orange (the image is the Hollywood area, with the W Hotel circled at Hollywood and Vine . When we link the two datasets for the use and age we can identify these for importers to check and redraw the new buildings.

**Comment by cityhubla** [comment]
There's a column in the assessors data that says how many buildings are on the property. After a count, there are about 20,996 buildings built after 2008 throughout the county. It's gonna be a fun import!

Here's a screenshot
![2014parcels](https://cloud.githubusercontent.com/assets/6407796/9023566/82d1990c-3855-11e5-8ab5-5139a705260f.jpeg)

**Comment by almccon** [comment]
@cityhubla Yes, we definitely want to start thinking about how to coordinate the manual updating after we do the import. We'd need to make sure that the license for the 2014 data is compatible, right? If so, we could set up a maproulette task to direct people to places on the map that need new buildings traced. We should think about filling this out in the "[updates](https://wiki.openstreetmap.org/w/index.php?title=Los_angeles,_California/Buildings_Import&action=edit&section=15)" section in the wiki, and track in issue #6.

**Comment by almccon** [comment]
Regarding the 2012 data we have at hand, do you think it's still worth using, @cityhubla? Even if it's not truly data that shows all the buildings in 2012, if it's an improved snapshot of 2008 we should still use it.

**Comment by cityhubla** [comment]
I would continue to use the 2008 set. The missing data in the 2012 set is the AIN (Assessor Identification Number) attributes are missing. We would need these to link to the AIN on the parcel data to get the building uses. Aside from what you and I found, I don't think its much of an improvement. 

I will contact County for licensing and using the 2014 set. I'll draft something and post for the "updates" section on the wiki.

**Comment by jschleuss** [comment]
@cityhubla @almccon I agree. Let's do a join to get the assessor data (there now is 2015 assessor data) and combine that with the 2008 file. I wouldn't waste time contacting the county. Mark says it'll be out of contract and posted online in a year. We can do updates then and just use the 2008 file to compare against newer buildings. But either way I say we hit this and make it happen! Yeah! I'm pumped.

**Comment by jschleuss** [comment]
LA City's data is the same as the 2008 data from the county. We've decided to move forward with that 2008 data until a new 2014 dataset is released sometime in 2016.
