### ISSUE TITLE
"Bad request" error using JOSM RC to download import file

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#114]
![](https://files.gitter.im/osmlab/labuildings/PHez/Screen-Shot-2016-12-22-at-11.17.53-AM.png)

This was reported by @jschleuss in gitter:

![screen shot 2016-12-26 at 15 35 34](https://cloud.githubusercontent.com/assets/353700/21480232/0a29ed68-cb81-11e6-8a86-31f2955b71f2.png)

Unfortunately, I cannot replicate the issue on my machine.

**Comment by samely** [comment]
I have the same message problem :(

**Comment by samely** [comment]
I've solved it by changing the auth mode from `use OAuth` to `Use Basic Authentication`

![image](https://cloud.githubusercontent.com/assets/10425629/22607403/bb4ea5f8-ea25-11e6-8fda-27c90c7868e7.png)

cc @jschleuss
