### ISSUE TITLE
Contact other LA County municipalities

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#12]
So, we had been planning to begin our import with the LA City census block groups first, and then proceed to other parts of the county. But, given our plans in #11 to ask the city for newer data (2014 instead of 2008), I was thinking that maybe we should start with other parts of the county first, while we're waiting to hear back from the City.

But then that got me thinking: are there any other municipalities in LA County that we should approach and ask for updated data? Are there any other cities that have progressive open data policies?

**Comment by almccon** [comment]
I don't know the political landscape of LA County very well, so maybe some other locals know which GIS departments we might approach, and which ones we shouldn't bother with. Tagging some of the @MaptimeLA people, in case they're not following this repo. @csterling @machikoyasuda @jschleuss @xta @JacquiSwartz

**Comment by jschleuss** [comment]
Well @csterling works for the city of Pasadena...so he must know something. :)

**Comment by gyllen** [comment]
Whats new on this issue? Is the import still going on?

**Comment by almccon** [comment]
The import is still in the preparation phase. We still need to finish processing the data, and then we need to consult with the OSM community before we can begin. 

I have almost finished making the necessary changes to convert.py, but I haven't had time recently to finish the job.

Regarding this issue specifically: we haven't contacted many other municipalities. We would love some help there. As I understand it, because the municipalities are part of the LARIAC consortium (which is the entity that releases the unified LA County building file) they might not be allowed to release their own data. Is that right @csterling?

**Comment by jschleuss** [comment]
Los Angeles County will release an updated file in 2016. We'll use the 2008 file going forward.
