### ISSUE TITLE
Kill off CODE=Courtyard in 2008 buildings file

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#16]
There are shapes for the courtyard, separate from the internal holes in the buildings. I vote we kick them out of the file.

**Comment by almccon** [comment]
Way ahead of you! ;) 

https://github.com/osmlab/labuildings/blob/eccba9f6c25fe426c729b14b354c2a8a6a9341b0/Makefile#L40

**Comment by jschleuss** [comment]
Awesome. I keep getting sidetracked but want to help out on this. I'm guessing next push is to combine with the assessor's data.
