### ISSUE TITLE
Building parts instead of building footprints?

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#19]
I downloaded the sample data mentioned [here](https://github.com/osmlab/labuildings/issues/9) and I noticed that some polys were divided into separate parts (i.e. balconies/terraces, roofs, etc).

![parts](https://cloud.githubusercontent.com/assets/353700/12063617/c4557372-afd7-11e5-9c48-9e880892caf5.gif)

At first I thought it was an isolated case, so I categorized the  data based on the `Shape_Area` field.  We have 96,738 buildings with less than 100 feet^2. 

Some looks like a legit free standing building (highlighted in yellow with a red dot):

![screen shot 2015-12-31 at 16 05 46](https://cloud.githubusercontent.com/assets/353700/12063649/75827bd6-afd8-11e5-8ea3-5ac44b3c4058.png)

But others are parts of a complex building:

![screen shot 2015-12-31 at 16 08 04](https://cloud.githubusercontent.com/assets/353700/12063678/ce91b188-afd8-11e5-8056-51e6e47ca52f.png)

This is the same for many areas (dots are buildings that are less than 100 feet^2):

![screen shot 2015-12-31 at 16 12 57](https://cloud.githubusercontent.com/assets/353700/12063713/6681e404-afd9-11e5-8a21-988c96af4e2e.png)

By default we trace buildings in OSM as a [single closed way/multipolygon](http://wiki.openstreetmap.org/wiki/Roof_modelling).  We can use this data for modelling [3D buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_buildings) but the attributes of the source data doesn't give us much info.

I made simple visualization showing the outlines of the buildings [here](https://api.mapbox.com/styles/v1/maning/ciglqvpbj000maakn5dz2lvb8.html?title=true&access_token=pk.eyJ1IjoibWFuaW5nIiwiYSI6IlhjWGNfdTQifQ.ras0nImWG638BCDSxU8bqw#18.55/34.12783/-118.15752).
(**OSM - Blue, LA County - Red. At low zooms, it shows building count at z15 tile**) 

I will investigate this further, but I would like to check here if the plan is to **import this as it is or we will do more pre-processing to merge building parts**.

cc/ @almccon @jschleuss @planemad

**Comment by planemad** [comment]
Ouch, first step is to understand why they are split. @maning do the parts have any different attributes from the main building that might have importance? And can we merge the footprints based on a common attribute?

**Comment by maning** [comment]
Initial look is that the only common attribute is `AIN` which is the parcel ID number. `AIN` is not a good attribute to reference merging. `BLDG_ID` is different for each polygon, hence, building parts would have different `BLDG_ID`s.

**Comment by almccon** [comment]
Also pinging @cityhubla.

@maning and @planemad, I think this is yet another bit of evidence that we should ignore the Pasadena data as part of this import. Given that the address data was messy (#9), and now the building polygons appear messy too, we should just skip it. Plus, the building data for Pasadena doesn't have heights attached, which makes these complex shapes even less useful for 3D modeling (see https://github.com/osmlab/labuildings/issues/3#issuecomment-67117627).

For the rest of the county, @maning your map of red dots for buildings less than 100 feet^2 isn't conclusive yet. Many of those might be legitimate free-standing garages and sheds. Also, did you filter out `CODE=Courtyard`? (see #16). We already have that filtered out in the Makefile.

**Comment by planemad** [comment]
From the latest sample output by @maning https://github.com/osmlab/labuildings/issues/14#issuecomment-171256316

I'm seeing more building parts, mostly attached to garages. Cannot find any patterns with the tags to filter these out, so our best bet might be by area. I measured the dimensions of quite a few and the most were in the 3-5 m2 range. 

<img width="607" alt="screenshot 2016-01-13 19 13 25" src="https://cloud.githubusercontent.com/assets/126868/12296278/bf9979dc-ba2c-11e5-8f63-dcbb8a826bd8.png">

cc @almccon

**Comment by planemad** [comment]
This seems like a really common issue throughout the sample

<img width="316" alt="screenshot 2016-01-14 15 45 39" src="https://cloud.githubusercontent.com/assets/126868/12321776/f8ddca6e-bad5-11e5-90a3-9ce6fd5f1261.png">
<img width="338" alt="screenshot 2016-01-14 15 46 09" src="https://cloud.githubusercontent.com/assets/126868/12321777/f8de96c4-bad5-11e5-9340-41d948e97f17.png">

In fewer cases these parts are connections between buildings

<img width="474" alt="screenshot 2016-01-14 15 48 12" src="https://cloud.githubusercontent.com/assets/126868/12321836/5970b684-bad6-11e5-858d-f0683bd5f257.png">

**Comment by cityhubla** [comment]
Hoping to close this issue, as discussed in #20, the multipolys that are building parts of a building is prevalent in the city of Pasadena and not the rest of the County. As this import now excludes Pasadena  I move we close this issue to move on.

**Comment by planemad** [comment]
@cityhubla lets be aware that there are building parts in the rest of the county as well as found in https://github.com/osmlab/labuildings/issues/19#issuecomment-171301786 but the issues is not as major as Pasadena.

:+1: for closing now

**Comment by almccon** [comment]
I just added a comment in the `IMPORTING.md` instructions to tell importers to look out for these.
