### ISSUE TITLE
Suppress Pasadena

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#20]
Based on all the problems we are seeing with the Pasadena address data (see #9) and the over-complex building shapes (see #19) which also lack heights (see https://github.com/osmlab/labuildings/issues/3#issuecomment-67117627), I recommend we skip Pasadena as part of this import. 

We can do this by skipping any features that have `Source=PASADENA.GIS`.

![screen_shot_2015-01-14_at_10 44 11_am](https://cloud.githubusercontent.com/assets/1212178/12065806/b5eddd78-af92-11e5-85e6-da63935fd8aa.png)

**Comment by cityhubla** [comment]
Happy new years! I've been searching for the state of Jefferson up in norcal. Reading up, I concur with setting Pasadena aside, we should look at the other sets, glendale and palmdale as they are sources along with Pasadena that was used to make the building outline datasst were using

**Comment by cityhubla** [comment]
From the county GIS [website](http://egis3.lacounty.gov/dataportal/2011/04/28/countywide-building-outlines/)

City of Palmdale – building outlines from the LAR-IAC (2006) imagery – derived from orthogonal imagery.

City of Pasadena – building outlines from earlier imagery, updated with LAR-IAC2 (2008) imagery in 2008

City of Glendale – building outlines from earlier imagery, updated with LAR-IAC2 (2008) imagery in 2008

City of Los Angeles – building outlines from LAR-IAC2 (2008), stereo generated, for all buildings > 64 square feet

The rest of the County – building outlines from LAR-IAC2 (2008), stereo generated, for all buildings > 400 square feet

**Comment by maning** [comment]
Suppressing Pasadena and Courtyards #27, we have **~299K out of ~314K buildings** to import.

**Comment by cityhubla** [comment]
Closing this issue per #23, Pasadena will not be imported at this time due to it's complex geometry.
