### ISSUE TITLE
Data offset

### ISSUE THREAD

**Issue by planemad** [osmlab/labuildings#25]
From the latest sample output by @maning https://github.com/osmlab/labuildings/issues/14#issuecomment-171256316

I'm noticing a slight but consistent offset of the data from the background of the order of 2m with both Bing and Mapbox imagery.

![untitled2](https://cloud.githubusercontent.com/assets/126868/12296117/aac2d28e-ba2b-11e5-994f-c212d6931e0d.gif)

GPS information is not accurate enough to verify the offset to this level. Should we ignore this and consider the data to be correct?

@almccon @maning

**Comment by maning** [comment]
Using a custom `-s_srs` parameter in ogr2ogr, I'm getting better results with the LA City 2014 building data #32 , see notes here: https://gist.github.com/maning/093a866fd465ea880032#better-conversion

**Next steps**
Run a test convert to all data layers (blocks, addresses, 2008 buildings) then, change reprojection script in the Makefile.

**Comment by planemad** [comment]
@maning the sample data matches Bing almost perfectly, and the offset with Mapbox imagery has reduced.

![untitled2](https://cloud.githubusercontent.com/assets/126868/12913252/9fc371b8-cf43-11e5-8d5f-9da6bf413b69.gif)

The projection looks good :+1:
