### ISSUE TITLE
Address to building matching is inconsistent

### ISSUE THREAD

**Issue by planemad** [osmlab/labuildings#26]
From the latest sample output by @maning https://github.com/osmlab/labuildings/issues/14#issuecomment-171256316

We're have quite a few addresses that get attached to the garage, while the address for the main building is still a node. Not sure if this is desirable.

<img width="460" alt="screenshot 2016-01-13 19 48 55" src="https://cloud.githubusercontent.com/assets/126868/12296592/b44b4d9c-ba2e-11e5-94b9-eccbea355ce1.png">

cc @almccon

**Comment by talllguy** [comment]
Seems like that row is shifted, like maybe the alignment is off there. The even addresses should be on the left, and the odd on the right, but the address points seem to be offset here by 10m or so. (assuming the gray line is a road).

**Comment by talllguy** [comment]
Hmm, I guess that wouldn't make sense with some of those nodes not aligning with anything on the other side. I am puzzled as to why the garages would be addressed separately though.

![2016-01-13 10_55_49-address to building matching is inconsistent issue 26 osmlab_labuildings](https://cloud.githubusercontent.com/assets/1827881/12299358/6006a618-b9e4-11e5-8b8a-103036ade6e0.png)

**Comment by planemad** [comment]
Found this 4 unit building `lacounty:bld_id=428646820599`

<img width="1043" alt="screenshot 2016-01-14 16 01 04" src="https://cloud.githubusercontent.com/assets/126868/12322240/d950e232-bad8-11e5-8f1a-0918961e2996.png">

Although one of the address `4015` has been attached, it still exists as a node, creating a duplicate address.

**Comment by planemad** [comment]
Found cases of colocated addresses

![untitled2](https://cloud.githubusercontent.com/assets/126868/12322931/62c8f334-badd-11e5-9f75-e0e23bd4ea1b.gif)

**Comment by planemad** [comment]
Inspecting various samples, most addresses don't seem to coincide with a footprint
<img width="520" alt="screenshot 2016-01-14 16 42 51" src="https://cloud.githubusercontent.com/assets/126868/12322997/efdfd42c-badd-11e5-8396-a57496dfd135.png">

**Comment by maning** [comment]
Closing. Let's revisit if we plan to import address in the future.
