### ISSUE TITLE
Preparing the Tasking Manager project

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#29]
The initial plan is to manage this import using [the Tasking Manager](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#check-out-a-task-on-the-tasking-manager). Ideally, using the osm.us instance.

We started developing the feature of being able to download the data in the TM. See [this demo](https://github.com/hotosm/osm-tasking-manager2/issues/734#issuecomment-173557292).

To be able to run this in osm.us instance, we need to merge this feature in TM's main code.  As per conversation with my colleagues (@batpad and @geohacker), this may not be possible if we want to get this rolling ASAP for two reasons:
* this feature is not a common use case for the TM and may not be merged to master,
* even if the community sees this as a good feature to implement, there is technical lift to prepare a PR and may delay our implementation.

Given the above scenario. I see two options:

1. **Deploy a separate TM instance with the download data feature just for this import.**
We can maintain this instance during the import process and for a limited time after the import. 
I made a sample running TM project here: **http://52.74.49.58:6543/project/15**

2. **Use the osm.us instance without this feature**.  We can prepare a document like a spreadsheet or wiki  where importers can download the data in their respective task.  This adds an overhead for those participating in the import, but I don't think its too much of hassle provided we give clear instructions in the import guidelines.

Lets use this ticket to discuss the pros/cons of the outlined options or, if there are other ways. 

@almccon  @jschleuss @cityhubla @planemad

**Comment by maning** [comment]
I prepared filtered blockgroups here: https://github.com/osmlab/labuildings/tree/master/task_blocks
* blockgroups_filtered.geojson (6,334 blocks) - full LA county blocks removing Pasadena and all blocks that don't have buildings.
* blockgroups_lacity.geojson (2,817 blocks) - LA City only blocks based on the DPW_CITY_BOUNDARIES shapefile.

We agreed to prepare the first import for LA city but loading all of LA city in one TM porject may slowdown the TM site.  

I propose we split LA City into several projects.  For example: downtown LA, north section, south section.

Other ideas?

![screen shot 2016-02-26 at 15 22 39](https://cloud.githubusercontent.com/assets/353700/13348965/cd7a4bca-dc9c-11e5-9e35-0ac6136d0e13.png)

**Comment by almccon** [comment]
Or maybe split into four: north section (The Valley), Westside, Eastside (central section including DTLA), and south section.

I suggest this mainly because Westside/Eastside is a common psychogeographic concept for most Angelenos.

**Comment by maning** [comment]
@almccon, I found [this](http://maps.latimes.com/about/) resource from LA Times it draws boundaries of neighborhoods for the whole LA County.  Should we use this?

![screen shot 2016-02-29 at 14 23 20](https://cloud.githubusercontent.com/assets/353700/13389747/4ef79a5e-def0-11e5-9680-c0cdc8dfd36d.png)

**Comment by planemad** [comment]
@maning ^ that looks like a great reference, we should go with this.

**Comment by maning** [comment]
@planemad, generated geojson's.

**Comment by almccon** [comment]
@maning looks great. Those regions don't line up with the LA City boundary, so are you thinking that we intersect those regions with the LA City boundary to get our first set of projects?

**Comment by maning** [comment]
For LA City only, here's the block groupings:

![screen shot 2016-03-01 at 14 58 45](https://cloud.githubusercontent.com/assets/353700/13423038/a35ec15c-dfbe-11e5-9465-4146966c81a8.png)

* [Eastside](https://github.com/osmlab/labuildings/blob/master/task_blocks/la_city_eastside.geojson) (1,322 blocks) - Eastside including greater downtown LA.
* [Southside](https://github.com/osmlab/labuildings/blob/master/task_blocks/la_city_southside.geojson) (207 blocks) - South bay and harbor.
* [Valley](https://github.com/osmlab/labuildings/blob/master/task_blocks/la_city_valley.geojson) (897 blocks) - San Fernando Valley and Northwest county.
* [Westside](https://github.com/osmlab/labuildings/blob/master/task_blocks/la_city_westside.geojson) (391 blocks) - Westside and Santa Monica.

Note that there are holes because according to LA County city boundaries, they are not part of LA City such as Beverly Hills and San Fernando City.

@almccon

**Comment by almccon** [comment]
Nice! 
Is the Eastside group small enough (with 1,322 blocks)? We could subdivide it further if necessary. Or maybe move the blocks that are in the South LA subregion from our Eastside into our Southside.

**Comment by cityhubla** [comment]
Can the groups be tasked? I'm wondering if the Southside can be our test for JOSM training and the Eastside for the mapathon. Are the blocks outside of LA City being included? The black dotted line on this image shows the boundaries for LA City.

![image](https://cloud.githubusercontent.com/assets/6407796/13451915/15eb914e-dff8-11e5-8018-7b19fea8f7d2.png)

**Comment by maning** [comment]
@almccon Moved blocks from eastside to southside.  All groupings are now under 1k.

![screen shot 2016-03-02 at 12 55 49](https://cloud.githubusercontent.com/assets/353700/13453454/4849a27e-e076-11e5-88ee-5c082b8b4873.png)

@cityhubla, 

> Can the groups be tasked? 

Yes, I'm just waiting for @iandees to migrate the current osm.us TM instance to have this download import data feature.  We are preparing a backup instance in case osm.us is not ready for the training and mapathon.

> Are the blocks outside of LA City being included? The black dotted line on this image shows the boundaries for LA City.

Not yet, we focus on LA City for initial import stage.

**Comment by iandees** [comment]
As far as I know the feature to load OSM data into the task via the geojson
has not been merged into the tasking manager repo. I don't feel comfortable
maintaining a fork that hacks the feature in and am waiting for it to be
merged before doing anything to tasks.openstreetmap.us.

**Comment by almccon** [comment]
@maning the new groupings look great to me!

@cityhubla, 
> I'm wondering if the Southside can be our test for JOSM training and the Eastside for the mapathon.

We could do this, or we could use the same grouping for both... since we don't know yet how long this will take, maybe we just try to funnel all the attention into just one of the groupings until it's mostly finished? I could go either way.

**Comment by maning** [comment]
Tasking Manager better slightly better URL: **http://labuildingsimport.com/**
Ideally we want it in the US TM instance, but the enhancement PR is not yet merged.  I agree with @iandees on not [merging this feature to US TM unless its in master](https://github.com/osmlab/labuildings/issues/29#issuecomment-191228745).  But since we have a mapathon this week, we wnet ahead to deploy a custom instance.

Let's discuss later how long we want to maintain this after the import.
