### ISSUE TITLE
Use 2014 LA City building data

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#32]
Use the new 2014 building data here: http://geohub.lacity.org/datasets/813fcefde1f64b209103107b26a8909f_0

Next steps:
- [x] Merge from attributes from Assessor data.
- [x] Review if data quality issues from 2008 is evident in this version.
- [x] Prepare sample data using the 2014 versions.

**Comment by planemad** [comment]
Going to take a stab at comparing the footprints tomorrow.

**Comment by maning** [comment]
2014 LA City building stats:
* Unchanged - 1,036,741
* Replacement - 6,152
* New - 12,092
* Modified - 54,253
* Total - 1,109,238

**Overall quality looks really good.**  Some observations below: 

![screen shot 2016-02-08 at 14 09 40](https://cloud.githubusercontent.com/assets/353700/12881214/07c7783a-ce6e-11e5-8540-6e9bb32a77d8.png)

Building complex tagged as separate adjoining buildings in OSM, map:  https://www.openstreetmap.org/#map=18/34.06634/-118.44328

![screen shot 2016-02-08 at 14 06 27](https://cloud.githubusercontent.com/assets/353700/12881215/07d3b032-ce6e-11e5-9bdc-6b464817e965.png)

Weird slivers, map: https://www.openstreetmap.org/#map=19/34.24951/-118.28962

![screen shot 2016-02-08 at 14 15 56](https://cloud.githubusercontent.com/assets/353700/12881288/a3e4c934-ce6e-11e5-9380-9daacb4bacd0.png)

Replaced buildings matches 2014-2015 Bing imagery, map: https://www.openstreetmap.org/#map=20/34.06524/-118.44460

![screen shot 2016-02-08 at 14 20 56](https://cloud.githubusercontent.com/assets/353700/12881354/50b9b9a8-ce6f-11e5-9457-89ad9367f8d2.png)

New buildings matches 2014-2015 Bing imagery, map: https://www.openstreetmap.org/#map=19/34.14808/-118.28917

**Comment by planemad** [comment]
This looks good @maning. Does Pasadena still have the building parts problem https://github.com/osmlab/labuildings/issues/19 ?

**Comment by maning** [comment]
> Does Pasadena still have the building parts problem #19 ?

@planemad, Pasadena is not part of LA City so I think this will be an issue.   I filtered all data that where modified/replaced/new with an area of <= 100 feet^2 (597 buildings).  Out of the 200 buildings I visually inspected, all of them a valid free-standing buildings.  I conclude that for the 2014 changes, building as part is not an issue, however, it is possible it is still present in the unchanged data.

**Comment by jschleuss** [comment]
I agree. It looks really solid. I'm gonna take a pass at removing the L.A. City buildings from the county file and replacing them with those files.

**Comment by maning** [comment]
@jschleuss Thanks for doing the merge!  Looking at the sample data now, I'm seeing duplicate building along the edge of LA City borders.  Running QGIS topology checker, we have 18 duplicates out of the 50,000 buildings in the sample data.

![duplicates](https://cloud.githubusercontent.com/assets/353700/13025905/6ca195b8-d23a-11e5-93b1-eaa3191ecf2c.gif)

You mentioned some issues of nixed buildings along the border, is this related?

> There were about 1,000 buildings that intersect with the boundaries of L.A. City. I was able to re-do the difference (in Arcmap, much faster) and I selected only polygons that were fully within the city. So, at worst some people will have missing buildings around the edges. But I don't think it'll be 1,000. It shouldn't be too bad.

**Comment by jschleuss** [comment]
@maning it should have been fixed. Hrm. Let me check. I'll see if I can't figure out a solution in the next few hours.

**Comment by jschleuss** [comment]
@maning OK. So there are 137 overlaps. Apparently L.A. City decided to draw some buildings outside of its boundary. I didn't anticipate that when I created the last merge. Should I recreate it? Or could we just add a note the import? If you think the latter will be a pain, I can re-kick out the file later tonight.

**Comment by maning** [comment]
>Should I recreate it? Or could we just add a note the import?

@jschleuss, I think its fine, I can check which blocks are affected and then add a note of these blocks.

**Comment by jschleuss** [comment]
I'll take a swing. There may be an issue with the data and buildings that appear to be pre-split right at the boundary. I'll check though.
