### ISSUE TITLE
Merge summary of discussion from github to OSM wiki

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#35]
For canonical reference to OSM wiki, we should merge/post summary of activities here to the OSM wiki:
https://wiki.openstreetmap.org/wiki/Los_angeles,_California/Buildings_Import

**Comment by talllguy** [comment]
Good idea. For my [Baltimore Co import](http://wiki.openstreetmap.org/wiki/Baltimore_County_GIS_Import) I merely pointed the wiki to [a GitHub Wiki](https://github.com/baltimorecounty/openstreetmap/wiki/Buildings-and-Addresses-Import). @maning do you think I should go back and copy over?

**Comment by maning** [comment]
I tried to capture a summary of what's happening over GH to the wiki: https://wiki.openstreetmap.org/wiki/Los_angeles,_California/Buildings_Import

**Comment by maning** [comment]
Done!
