### ISSUE TITLE
Google Docs is not readable

### ISSUE THREAD

**Issue by drkludge** [osmlab/labuildings#38]
The https://github.com/osmlab/labuildings page points to this page
https://docs.google.com/spreadsheets/d/1A3whba04_-3K0z77nGHYavIwYpWjnyAaInwWie3HSVA/edit#gid=1971401153 .  The page says, "You need permission  Want in? Ask the owner for access, or switch to an account with permission."

**Comment by cityhubla** [comment]
@drkludge, i set it for viewing to the public, does it work now?

**Comment by drkludge** [comment]
Thank you.  I can read the document now.
