### ISSUE TITLE
Planning for a local mapathon in the Los Angeles Metropolitan Area

### ISSUE THREAD

**Issue by cityhubla** [osmlab/labuildings#39]
This is to plan and set a date for a OSM mapathon to bring about a community effort for this import.

I will be doing outreach to local mappers and organizations and refer them to this import, repo, and this issue for helping to plan or distribute a date for mapping either at a location or throughout the Los Angeles area. There will be some beginners who may not be familiar with JOSM to facilitate the import, so there will be a tutorial session, perhaps hosted by [maptimeLA](http://www.meetup.com/maptimela/) in advance of the scheduled mapathon.

I will reach out to these orgs with more to follow:
[OSM Southern California](http://www.meetup.com/OSM-Southern-California/)
[maptimeLA](http://www.meetup.com/maptimela/)
[LA County GIS Department](http://egis3.lacounty.gov/dataportal/)
[SocalGIS](http://socalgis.org/)
[Geospatial @ UCLA](http://gis.ucla.edu/)
[USC Dornsife Spatial Sciences Institute](http://gis.usc.edu/)
[Cal State LA Department of Geosciences and Environment](http://www.calstatela.edu/academic/geos)
[HackforLA](http://www.hackforla.org/)
The organizers of [OpenStreetMap US Summer Mapathon 2014](http://www.meetup.com/OSM-Southern-California/events/196636252/), which was set in LA.
[LA Times](http://www.latimes.com)

If I'm missing any group, let me know.

**Comment by maning** [comment]
Great! referencing: https://github.com/osmlab/labuildings/issues/23

**Comment by lxbarth** [comment]
+add LA Times! I can make an intro if needed.

**Comment by cityhubla** [comment]
@lxbarth, thanks! And yes please if you could do the intro, you can post here as a .md file

**Comment by almccon** [comment]
@lxbarth @cityhubla don't we already have a contact at the LA Times? Right @jschleuss? ;)

**Comment by cityhubla** [comment]
Posting this link referencing mapathons [US_Winter_Mapathon](http://wiki.openstreetmap.org/wiki/Mapathon/US_Winter_Mapathon_2016), we may need to email the [OSM.us board](board@openstreetmap.us) of the event.

**Comment by cityhubla** [comment]
maptimeLA can host a OSM/JOSM tutorial on either March 31st, April 14th or April 28th at ARUP's offices in downtown LA. I'm wondering if we need a bigger venue, our capacity there is about 35.

These dates can be followed up with the mapathon the week after at LATIMES HQ, @jschleuss if we can get logistics about timing, security and such. During the mapathon we should set some time pregame for beginners before the mapping begins and set aside a group with mentors and beginners.

**Comment by cityhubla** [comment]
Here is the draft outreach letter, [Draft Outreach Letter](https://docs.google.com/document/d/1Eg5O6HrRxNVKtlazadQYLTd_sLlRB7NBQTEVTMSCdQ0/edit?usp=sharing)

Feel free to comment and edit, as I know I may be missing some items or unclear at certain areas.

**Comment by jschleuss** [comment]
@almccon @lxbarth @cityhubla yep! I'm a reporter/graphic artist/mapper and have confirmed we can use our community room. We just have to figure out a date/time and see if that works for the scheduling of that space. Which date should I ask about?

**Comment by jschleuss** [comment]
Alrighty. Godwilling, we have plans to start local importing with these events:

- **March 31, 2016 @ 6:30 p.m.:** [MaptimeLA](http://www.meetup.com/MaptimeLA/) will host a JOSM training and kickstart event for importing. As always, there'll be a huge pizza.
- **April 2, 2016 @ 12:00 p.m.:** The Los Angeles Times [graphics](https://twitter.com/latimesgraphics)/[data](https://twitter.com/LATdatadesk) desks will host a mapathon to teach JOSM and importing with the task manager. Even more pizza will also be provided!

**Comment by cityhubla** [comment]
I've posted two events on meetup, one for training and one for the mapathon with training

[It's an OpenStreetMap kinda night!, March 31st @6:30pm PST](http://www.meetup.com/MaptimeLA/events/229861006/)

[It's an OpenStreetMap mapathon! with LA's Buildings! at the LA Times!, Saturday April 2nd from 12-4pm PST](http://www.meetup.com/MaptimeLA/events/229861154/)

**Comment by cityhubla** [comment]
Ok i sent outreach emails to

LA County GIS Department
SocalGIS
Geospatial @ UCLA
USC Dornsife Spatial Sciences Institute
HackforLA

**Comment by machikoyasuda** [comment]
@jschleuss serious question: everyone (okay, 1 person) is asking me where you bought the pizza from Apr. 2nd from. where was it from??

**Comment by jschleuss** [comment]
Pizza Next Door
806 W 8th St, Los Angeles, CA 90017
https://maps.google.com/?q=Pizza%20Next%20Door%2C%20806%20W%208th%20St%2C%20Los%20Angeles%2C%20CA%2090017&ftid=0x80c2c7b6c3eaf32b:0x8b042a952e4f83d&hl=en-US&gl=us

**Comment by maning** [comment]
All done here. Closing.
