### ISSUE TITLE
List of usernames participating in the import

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#40]
List here your OSM usernames, for details, read the [import guideline](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#creating-an-import-account)

**Comment by meetar** [comment]
meetar_imports
:hand:

**Comment by almccon** [comment]
[Alan_imports](http://osm.org/user/Alan_imports)

**Comment by cityhubla** [comment]
[omaru_imports](https://www.openstreetmap.org/user/omaru_imports)

**Comment by jschleuss** [comment]
[schleuss](https://www.openstreetmap.org/user/schleuss)

**Comment by almccon** [comment]
@jschleuss according to the import guidelines we are supposed to create a separate account for imports... something like `schleuss_imports`

**Comment by aaronlidman** [comment]
[aaron_imports](http://www.openstreetmap.org/user/aaron_imports)

**Comment by palewire** [comment]
palewire --> https://www.openstreetmap.org/user/palewire/

**Comment by joemfox** [comment]
[joemfox_imports](http://www.openstreetmap.org/user/joemfox_imports)

**Comment by kyleykim** [comment]
[kyle_imports](http://www.openstreetmap.org/user/kyle_imports)

**Comment by EbenMcCue** [comment]
ebenmccue_imports

**Comment by priyakkumar** [comment]
[priya_imports](http://www.openstreetmap.org/user/priya_imports)

**Comment by LElebee** [comment]
[Elebee_imports](https://www.openstreetmap.org/user/Elebee_imports)

**Comment by rullian** [comment]
[deadlands_imports](https://www.openstreetmap.org/user/deadlands_imports)

**Comment by aquintero4354** [comment]
https://www.openstreetmap.org/user/aquintero4354

**Comment by aquintero4354** [comment]
https://www.openstreetmap.org/user/aquintero_imports

**Comment by CartoonKahuna** [comment]
My user name is [Dugi_Imports](https://www.openstreetmap.org/user/Dugi_Imports)

**Comment by tbone** [comment]
[thomas06037_imports](https://www.openstreetmap.org/user/thomas06037_imports/account)

**Comment by maning** [comment]
[manings_labuildings](http://www.openstreetmap.org/user/manings_labuildings)

**Comment by emamd** [comment]
[emamd_imports](http://www.openstreetmap.org/user/emamd_imports)

**Comment by kingrollo** [comment]
kingrollo_imports

**Comment by MtnBiker** [comment]
MtnBiker_imports

**Comment by eirinikos** [comment]
andrea_imports

**Comment by machikoyasuda** [comment]
(machiko_imports)[http://labuildingsimport.com/user/machiko_import]

**Comment by ericpritchett** [comment]
ericpritchett_import

**Comment by schmeltz** [comment]
schmeltzer_import

**Comment by kennethlee** [comment]
kennethlee_import

**Comment by anthonyjpesce** [comment]
anthonyjpesce_imports

**Comment by WalkieTalkieLA** [comment]
WalkyTalkyLA_imports

**Comment by bdon** [comment]
bdon_import

**Comment by michaelkirk** [comment]
michael_kirk_imports

**Comment by planemad** [comment]
`planemad_imports`

**Comment by chtnha** [comment]
[chetan_labuildings](http://www.openstreetmap.org/user/chetan_labuildings)

**Comment by jinalfoflia** [comment]
[jinalfoflia_labuilding](http://www.openstreetmap.org/user/jinalfoflia_labuilding)

**Comment by nikhilprabhakar** [comment]
[nikhil_labuildings](https://www.openstreetmap.org/user/nikhil_labuildings)

**Comment by ruthmaben** [comment]
ruthmaben_labuildings

**Comment by ramyaragupathy** [comment]
[ramyaragupathy_imports](http://www.openstreetmap.org/user/ramyaragupathy_imports)

**Comment by karitotp** [comment]
[karitotp_labuildings](http://www.openstreetmap.org/user/karitotp_labuildings)

**Comment by Rub21** [comment]
[Rub21_labuildings](https://www.openstreetmap.org/user/Rub21_labuildings)

**Comment by dannykath** [comment]
[dannykath_labuildings](https://www.openstreetmap.org/user/dannykath_labuildings)

**Comment by luiswalter** [comment]
Luis36995_labuildings

**Comment by samely** [comment]
[samely_labuilding](http://www.openstreetmap.org/user/samely_labuilding)

**Comment by RichRico** [comment]
[RichRico_labuildings](http://www.openstreetmap.org/user/RichRico_labuildings)

**Comment by calfarome** [comment]
[calfarome_labuilding](http://www.openstreetmap.org/user/calfarome_labuilding)

**Comment by ediyes** [comment]
[ediyes_labuilding](http://www.openstreetmap.org/user/ediyes_labuilding)

**Comment by mihaigdev** [comment]
mihaig_imports

**Comment by kmw** [comment]
kmw_import

**Comment by wtalaro** [comment]
ecoliteracy_import

**Comment by jsakota** [comment]
Juhyun_import

**Comment by ridixcr** [comment]
[ridixcr_import](http://www.openstreetmap.org/user/ridixcr_import)

**Comment by scottgruber** [comment]
scottgruber_import

**Comment by ianlopez1115** [comment]
[ianlopez1115_imports](https://www.openstreetmap.org/user/ianlopez1115_imports)

**Comment by noflag** [comment]
devolved_imports

**Comment by maanyaumashaanker** [comment]
maanya_imports

**Comment by poornibadrinath** [comment]
poornima_labuildings

**Comment by piligab** [comment]
[piligab_labuildings](https://www.openstreetmap.org/user/piligab_labuildings)

**Comment by abhisheksaikia** [comment]
[saikabhi_LA_imports](https://www.openstreetmap.org/user/saikabhi_LA_imports)

**Comment by jothirnadh** [comment]
Jothirnadh_labuildings

**Comment by krishnanammala** [comment]
nammala_labuildings

**Comment by manoharuss** [comment]
[manoharuss_imports](http://www.openstreetmap.org/user/manoharuss_imports)

**Comment by Yurasi** [comment]
[yurasi_import] (https://www.openstreetmap.org/user/yurasi_import)

**Comment by jihoonchoi724** [comment]
wwtoonlinkfan_imports

**Comment by kupendrayadav** [comment]
upendra_labuilding

**Comment by Fa7C0n** [comment]
Fa7C0N_imports

**Comment by bsrinivasa** [comment]
[BharataHS_laimport](https://www.openstreetmap.org/user/BharataHS_laimport)
