### ISSUE TITLE
Add AIN (assessor parcel number) to buildings

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#50]
Earlier we decided to drop it on import, but several of my colleagues have asked for it. It would allow future users of the data to combine with other data from the assessor or by state. The AIN is a 9-digit number. Could we discuss bringing that into the import? It should already be in base footprint shapefile.

**Comment by maning** [comment]
I'll do this for the sample data. What tag should I use? Would `lacounty:ain` suffice?
Note that not all buildings have AIN.

**Comment by jschleuss** [comment]
@maning Yep! I think that'd be great. It'd work with the `lacounty:bld_id` we already have in there.

**Comment by maning** [comment]
Rebuilding the data.
