### ISSUE TITLE
Conflation process for previous building import by other users in LA

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#53]
Per [mailinglist discussion](https://lists.openstreetmap.org/pipermail/imports/2016-March/004365.html), some users in LA county have started importing LARIAC building data.

Using this overpass query: http://overpass-turbo.eu/s/eZx, 7255 buildings were added by several user
![screen shot 2016-03-14 at 10 09 23](https://cloud.githubusercontent.com/assets/353700/13735224/eaf66b42-e9cc-11e5-903d-bc18a8427b39.png)

![screen shot 2016-03-14 at 10 09 01](https://cloud.githubusercontent.com/assets/353700/13735223/eaf5becc-e9cc-11e5-81b3-d0cb6dae1bb5.png)

Next steps

- [ ] contact users and inform them of our import plans
- [ ] evaluate quality of the data and what tags were imported
- [ ] define a process of conflation in line with the import plans

**Comment by jschleuss** [comment]
@maning HA! That looks to be about 99% me. My plan is to take the blocks in East Hollywood and Catalina Island to fix them all. I was ignorant about the proper OSM tags at the time. I feel bad for all the people who came behind me to fix simple things like uppercase tags. [Some still exist](http://overpass-turbo.eu/s/f1t). 

The only other person that appears to be doing the imports from the building file is [mattmaxon](http://www.openstreetmap.org/user/mattmaxon). I'll reach out to that user with an email asking for help and letting him know about our plan. 

Separately, I've been importing small amounts of [parking lots](http://egis3.lacounty.gov/dataportal/tag/parking-lots/) when I can. Usually a neighborhood at a time if they match satellite images. I've only gotten through East Hollywood and Westmont in South L.A. That's alright, right? I'm at least following proper tagging and it's in small batches.

**Comment by jschleuss** [comment]
I have mixed feeling with dealing with conflation. For example, this building was added a couple of months ago by a Mapbox tracer (I think it was traced). It's extremely accurate in its shape. But it has no tags save building=yes. I really hate deleting work by others, but I would prefer to see more data associated with these ways. Would it be insane to replace all those shapes? Is there an easy way could select items and tag them based on the data separately?

**Comment by n76** [comment]
With respect to accurately traced existing buildings but lacking all desired tags: Open you import data in JOSM, then download the existing OSM data IN A NEW LAYER. You can adjust the layer transparencies so that you can see both layers and see the conflicts. For an existing building:

1. Copy the tags from the import layer version.
2. Delete the building from the import layer.
3. Switch to the OSM layer.
4. Select the building, paste the tags.

Wash, rinse and repeat for all conflicts.

You will end up with two layers: A OSM layer with updated tagging but no new objects (one commit to make) and a new layer with non-conflicting additions (another commit to make).

**Comment by jschleuss** [comment]
I like this.

**Comment by maning** [comment]
> The only other person that appears to be doing the imports from the building file is mattmaxon. I'll reach out to that user with an email asking for help and letting him know about our plan.

@jschleuss Any update on :point_up: ?  We can close if nothing here is actionable.

**Comment by jschleuss** [comment]
@maning Let's close. We'll attempt to keep a rolling communication with anyone related throughout the import.

**Comment by almccon** [comment]
@jschleuss check out https://wiki.openstreetmap.org/wiki/San_Francisco_Building_Height_Import.

@bdon is working on some scripts that do smart conflation of attribute data with hand-traced footprints that already exist in OSM. Maybe we could adapt that (when it's finished) and do semi-automated conflation with the existing OSM data? It would make things quite a bit faster than the workflow that @n76 describes.

**Comment by dkogan** [comment]
Alan McConchie <notifications@github.com> writes:

> @jschleuss check out
> https://wiki.openstreetmap.org/wiki/San_Francisco_Building_Height_Import.
>
> @bdon is working on some scripts that do smart conflation of attribute
> data with hand-traced footprints that already exist in OSM. Maybe we
> could adapt that (when it's finished) and do semi-automated conflation
> with the existing OSM data? It would make things quite a bit faster
> than the workflow that @n76 describes.

The existing tools are usable. See

  https://github.com/osmlab/labuildings/issues/67

I worked through all the merge-heavy tasks in the South LA set that's up
so far, and I intend to keep focusing on those as they come up. Let's
talk about workflows during the next meeting.

**Comment by maning** [comment]
Logging here overpass query for imports buy matmaxxon: **http://overpass-turbo.eu/s/gE2**

**Comment by maning** [comment]
Here's the status so far, will update this table as we go along fix them.

| Query | Number of features |
| --- | --- |
| http://overpass-turbo.eu/s/eZx |  1048 |
| http://overpass-turbo.eu/s/gE2 | 30 |

**Comment by maning** [comment]
I added a fixme tag to [mattmaxon's](http://www.openstreetmap.org/user/mattmaxon) imported data. @jschleuss, did mattmaxon ever responded to your messages?

The affected area is west of Angeles National Golf Club. **~2275 ways were imported**. This area is not yet part of the current TM projects, we will conflate them when a TM project passes over the area. 

Issues with mattmaxon's import are the following:
* building offset we encountered before and fixed in the processing of shapefile to osm.
* incorrect tags ( `TYPE` and `NOTES`)
* duplicated ways
* untagged ways 


![screen shot 2016-06-15 at 16 49 59](https://cloud.githubusercontent.com/assets/353700/16077927/6764b806-3319-11e6-889f-17f401605895.png)

![screen shot 2016-06-15 at 16 49 36](https://cloud.githubusercontent.com/assets/353700/16077928/678b85bc-3319-11e6-9f8a-0a170fb592d8.png)

My changeset adding a fixme tag are the following:

* https://www.openstreetmap.org/changeset/40036210
* https://www.openstreetmap.org/changeset/40036538

**Comment by jschleuss** [comment]
@maning I never heard back. Reaching out again.

To fix my previous imports I just deleted every building on the map. If a building had some better tags than (ELE, HEIGHT, or what comes with the building shapefile) I'd copy the tags over, like business name or address. And then replace with the new import layer.

**Comment by maning** [comment]
This is done, cleanup in progress to catch others in case we missed some.
