### ISSUE TITLE
Don't include non-numeric building:levels

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#64]
@n76 and I noticed a lot of `building:levels = <4` in our tasks (http://labuildingsimport.com/project/2#task/464 and http://labuildingsimport.com/project/2#task/206).

The JOSM validator doesn't like these. If we regenerate the chunks, we should exclude these.

**Comment by n76** [comment]
I've also found some `building:levels = >4` in other tasks. Seems like anything with a ">" or "<" should not be included.

**Comment by maning** [comment]
The attributes we get these are from [4 Stories or Less](https://github.com/osmlab/labuildings/blob/master/mappings_csv/Specific_1.csv#L2) and [5 Stories or more](https://github.com/osmlab/labuildings/blob/master/mappings_csv/Specific_1.csv#L3) of the SpecificUseDetail field.

There are no numeric value for this other than above values. We've [discussed this before](https://github.com/osmlab/labuildings/issues/43#issuecomment-194957204) and we agreed to keep it for now.  

I'm OK removing this in the next run.  Is this something that should stop the current import of Southside LA? 

We can remove `building:levels` in the currently imported in OSM and then re-run the full LA data without this tag.

**Comment by almccon** [comment]
Thanks for the link to the previous discussion, @maning. I missed that. Also, I didn't realize that the data was so coarse. So `<4` and `>4` are the only possible values we have in our import data? That doesn't seem useful enough to keep... for the vast majority of cases you could deduce this value based on the building height. 

Looking at taginfo, non-numberic values are extremely rare: https://taginfo.openstreetmap.org/keys/building:levels#values In fact, I think our `<4` are _almost_ the only ones. 

I don't think this is serious enough to halt the current Southside TM project. I think we should do this:
1. Recommend that our manual importers remove this tag before importing (but it's okay if they forget)
2. Validators remove this tag from any LA buildings that get imported.
3. We re-run the full LA data without this tag and use that for all the future TM projects.

**Comment by jschleuss** [comment]
I agree with @almccon. @maning and I had previously thought to keep it, but it is creating a large number of warnings and it's use is quite limited.

**Comment by cityhubla** [comment]
I'm with at @almccon proposes with the steps, and leave it out when we expand citywide

**Comment by maning** [comment]
OK.  Made changes in the code, sample data, wikipage.  Rebuilding the full data now.  Will close once done.

**Comment by maning** [comment]
Data rebuild done.  Please check some data in the TM.  **Close** if no `building:levels` exist.

**Comment by maning** [comment]
We all good here. Closing.
