### ISSUE TITLE
Bug in import script: multiple duplicated nodes in some ways

### ISSUE THREAD

**Issue by dkogan** [osmlab/labuildings#68]
Hi. Please look at buildings-addresses-060372402003.osm. Look at way -519 (ain = 6040013035). Note that there are two pairs of duplicated nodes here: -4319 and -4054. Clearly -4319 was meant to close the loop, but -4054 is a bug. This bug results in the JOSM validator throwing a mysterious error that make no sense at all until you look at the internal data. Currently the only way to resolve this is to delete the node in JOSM, and create a new one in the same place.

**Comment by dkogan** [comment]
I should also note that this isn't an isolated case: I hit a few of these yesterday.

**Comment by maning** [comment]
@dkogan, Thanks for flagging this. I'll investigate closely.
