### ISSUE TITLE
Some duplicate building ways near block group borders

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#70]
I've seen this occasionally when a block group border slices through a building. Validation will reveal that there are duplicate buildings on top of each other.

**Comment by cityhubla** [comment]
@jschleuss, this looks like what @dkogan was speaking to in #68

**Comment by jschleuss** [comment]
@cityhubla no, I think this is different. I'm seeing more than just duplicate nodes. I'm seeing duplicate ways (sometimes with about a dozen nodes linked together with tags).

**Comment by maning** [comment]
@jschleuss Not sure if I get it right.  
The way the `chunk.py` works is that it gets all the buildings that [intersects the census block boundary](https://github.com/osmlab/labuildings/blob/master/chunk.py#L42).  So for example if a building touches two census blocks, it will be in both `buildings-addresses-xxxxx.osm` file.  When you upload the first one then another uploads the adjacent file there will be duplicates and the former user should delete the duplicates.  Is this the scenario you are seeing? Or, do you mean that duplicated ways exist in a single import file?

**Comment by jschleuss** [comment]
@maning I think that's all I was seeing. The intersecting buildings with the border of the block group. I'm going to close this issue. I haven't seen it independent from the buildings already in the OSM data.
