### ISSUE TITLE
Create guide for validation

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#73]
Right now, we don't have guidelines for validation.  Basic outline should include:
1. How to fix common errors.
2. How to merge splitted shapes . https://github.com/osmlab/labuildings/issues/71
3. How to merge overlapping buildings, etc.
4. Add missing buildings from imagery.
5. Remove demolished buildings based on imagery.
6. Remove duplicates: https://github.com/osmlab/labuildings/issues/70
7. etc.

**Comment by jschleuss** [comment]
Do we want to address JOSM warnings about things other than the building import? I'm seeing a few one way streets with a -1 "direction" and "route has no name" type errors.

**Comment by almccon** [comment]
@jschleuss I think we don't _have_ to fix those, but if you do, that's great. It's a good argument in favor of imports if we can say that the import process leads to a close inspection of other OSM features which get fixed along the way.

For example, @lxbarth mentioned that the NYC buildings import "fixed over 5,000 unrelated map issues along the way". http://www.openstreetmap.org/user/lxbarth/diary/23588

**Comment by dkogan** [comment]
Ugh, can we please do that as a separate changeset? The current workflow makes it difficult to answer such basic questions as "where did the data for this building come from?" and putting even more stuff into these changesets makes this even worse. We can have a separate set of mapping tasks dedicated to fixing validation errors, if we want to do that.

When you explicitly run the validator in JOSM, it checks all the data in the layer, even if it is untouched and will not be uploaded. I think this is counterproductive to the _import_ effort. Instead one can ask JOSM to upload (C-S-up); it will then run the validator only on the data being uploaded, which is what we want, I think.

**Comment by jschleuss** [comment]
@dkogan I'm mixed. I think it's not necessary to require anyone to do any extra work beyond the specific import. But I'm making fixes when I can. It just seems like the right thing to do. It's likely these areas won't be touched/fixed for some time. But we could definitely make that a large task in the future. 

Building info like building=house, building:units and start_date all come from a join with the [assessor's parcel file](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2015/hvzm-fn38). The height and elevation are pulled directly from the shapefile, which is a combination of the [2008 LARIAC county file](http://egis3.lacounty.gov/dataportal/2011/04/28/countywide-building-outlines/) and the [2014 L.A. City LARIAC file](http://geohub.lacity.org/datasets/813fcefde1f64b209103107b26a8909f_0).

**Comment by jschleuss** [comment]
More here https://github.com/mapbox/mapping/issues/170
