### ISSUE TITLE
grids being imported

### ISSUE THREAD

**Issue by talllguy** [osmlab/labuildings#76]
This could be unrelated, but I saw this untagged way and thought it could have been an import grid that was inadvertently added. :question:  https://www.openstreetmap.org/way/370586773#map=16/33.8560/-118.2841

**Comment by dkogan** [comment]
Elliott Plack <notifications@github.com> writes:

> This could be unrelated, but I saw this untagged way and thought it
> could have been an import grid that was inadvertently added.
> :question:
> https://www.openstreetmap.org/way/370586773#map=16/33.8560/-118.2841

This is just a silly contribution by a beginner. Not related to the
import

**Comment by talllguy** [comment]
Removed :x:
