### ISSUE TITLE
Add missing buildings?

### ISSUE THREAD

**Issue by meetar** [osmlab/labuildings#78]
From https://github.com/osmlab/labuildings/blob/master/IMPORTING.md:

> Newer building should be identified and flagged. (This process should not be done, pending approval and recommendations from the OSM Community.) Tag the building with fixme and add a note: Appears in satelite imagery. 

Getting mixed messages here. Should this be done or not?

**Comment by maning** [comment]
@meetar, Thanks for flagging.  I clarified this in the importing guide.

**Comment by meetar** [comment]
:+1: Thank you!
