### ISSUE TITLE
How to deal with unittype?

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#8]
The address data has a "unittype" field. This is for whether a unit should be described as "#300" or "Unit 300" or "Apartment 300". 

Most of the time this doesn't matter, but it looks like there are a few rare cases where we wouldn't want to discard this.

Here are the possible values for unittype (other than null) and the number of times they occur in the address file:

```
UNIT      233998
APARTMENT 46952
#         17398
SUITE     3841
SPACE     417
ROOM      186
APT       128
REAR      83
BOX       15
BACK      7
FRONT     6
MAILBOX   5
PH        5
LOT       2
COTTAGE   2
PARKING   1
FRNT      1
```

I think for most of these (like unit, apartment, 3, suite, etc) we can ignore them. Maybe only "front" and "back" might be significant, and can be handled manually?

**Comment by talllguy** [comment]
There is a key for these `addr:unit=fu` ([taginfo](http://taginfo.openstreetmap.org/keys/?key=addr%3Aunit#overview)). Are there a bunch of stacked address points with different units, e.g. for the downtown high-rises?

**Comment by talllguy** [comment]
Ah, #8 deals with my question in the above. For nodes with units that are spatially separate from others, I don't think it'd be bad to keep them. In Baltimore County, A/B/C etc and fractionals are typically appended to the housenumber. The unit would usually only be used for office suites or apartments.

**Comment by almccon** [comment]
Well, we already have apartment number letter postfixes that are included in `unitname`, and fractional addresses are included in `numsuffix`, and I'm just appending those to the street number. 

What I'm asking about here is this field for the unit type, not the unit number. I don't see any way to tag in OSM whether `addr:unit` is called a "unit" or an "apartment" or a "suite"...

**Comment by maning** [comment]
Closing, lets re-open if we intend to import address in the future.

**Comment by talllguy** [comment]
@maning: is there an issue here somewhere that contains the discussion to not include addresses?

**Comment by maning** [comment]
@talllguy: yes, see: https://github.com/osmlab/labuildings/issues/23
