### ISSUE TITLE
Lots of duplicated buildings for http://labuildingsimport.com/project/2#task/456

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#83]
[This import data](http://labuildingsimport.com/project/2#task/456) has a lot of duplicate nodes/ways.  Not sure what's the issue. Flagging in this ticket for further investigation.
![screen shot 2016-04-20 at 19 50 31](https://cloud.githubusercontent.com/assets/353700/14677920/57484898-0731-11e6-9513-e38d30216c0e.png)

**Comment by jschleuss** [comment]
It looks like a small issue with the city's more recent [building shapefile](http://geohub.lacity.org/datasets/813fcefde1f64b209103107b26a8909f_0). I can only find three other locations where this happens, but each of those just have one duplicate building, not the entire area. The attributes should be the same on all those you see @maning 

<img width="593" alt="screen shot 2016-04-20 at 3 25 24 pm" src="https://cloud.githubusercontent.com/assets/695934/14692469/43ed5394-070c-11e6-9f22-1183028a81f9.png">
<img width="551" alt="screen shot 2016-04-20 at 3 25 18 pm" src="https://cloud.githubusercontent.com/assets/695934/14692472/44137790-070c-11e6-943e-efa974558568.png">
<img width="496" alt="screen shot 2016-04-20 at 3 25 00 pm" src="https://cloud.githubusercontent.com/assets/695934/14692471/4411a852-070c-11e6-8af7-8395f9acbe3a.png">
<img width="409" alt="screen shot 2016-04-20 at 3 22 52 pm" src="https://cloud.githubusercontent.com/assets/695934/14692470/4410d882-070c-11e6-8fcd-05daa1251b98.png">

**Comment by maning** [comment]
I worked on this specific task and fixed the duplicates before uploading.  The other 2 places should be fixed as we do validation. Closing
