### ISSUE TITLE
Imagery in JOSM

### ISSUE THREAD

**Issue by utack** [osmlab/labuildings#84]
Hi,

can't get the images to load in JOSM
Anything I did wrong there?
![bildschirmfoto vom 2016-04-22 17-45-11](https://cloud.githubusercontent.com/assets/8551234/14746873/019c158c-08b2-11e6-872a-b6755afb881e.png)
Thanks

**Comment by maning** [comment]
Hi @utack, does it load when you use the Tasking Manager (Edit with JOSM)?

**Comment by utack** [comment]
No, it only loads a layer with borders or each task automatically

**Comment by maning** [comment]
Ah yeah, you need to [manually add Bing imagery](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md#adding-bing-imagery-background).

**Comment by utack** [comment]
Wait, what. I just need the normal Bing layer, that is pre-configured in JOSM, not any mapbox layer?

**Comment by maning** [comment]
So when you open JOSM, you load the Bing imagery.
* From the **Imagery** menu, select **Bing aerial imagery**.
* Get a task in the TM, click **Edit with JOSM**

Hope that helps.

**Comment by utack** [comment]
It does.
Still have not understood what the custom url provided in the task is for, but I can use bing
