### ISSUE TITLE
Misaligned buildings with Bing

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#87]
While reviewing [one task](http://labuildingsimport.com/project/3#task/256), I noticed misaligned buildings with Bing.

![alignment](https://cloud.githubusercontent.com/assets/353700/15015491/d7a97d24-1229-11e6-951b-b11d60313a34.gif)

This is the mountainous area of LA and the imagery maybe distorted due to the terrain.  The building aligns very well with the USGS Large Scale Imagery.

**Comment by jschleuss** [comment]
That's strange. I've noticed a few weird spots, but I lean on trusting the data. You can see the misaligned adds from people using Yahoo imagery 6 years ago.
