### ISSUE TITLE
Temporary pause on importing for next two weeks!

### ISSUE THREAD

**Issue by almccon** [osmlab/labuildings#88]
Hi everyone, we've been asked to pause our import for the next couple of weeks. The OSM server team is working to back up the database in preparation for some server downtime on May 9th ([more info here](https://blog.openstreetmap.org/2016/05/02/planned-server-outage-9th-may/)). Apparently the servers are overloaded right now, so they asked us to pause our uploads, which are very large (including thousands of features at a time).

Normal editing is okay, it's just the imports that we need to hold off on. 

I'll update this issue when we get the all-clear from the sysadmins.

**Comment by maning** [comment]
- [ ] @maning to add a temporary announcement at labuildingsimport.com

**Comment by maning** [comment]
we are back! closing.
