### ISSUE TITLE
Buildings removed in Southside block

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#90]
I've deleted buildings added in [this task](http://labuildingsimport.com/project/2#task/54) after being alerted to their removal by [Christine_E](https://www.openstreetmap.org/user/Christine_E/). 

She's been to the area and confirms that the area has been leveled, which is also reflected in Bing's satellite imagery from late 2014. It looks like the property was military housing and sold off to a developer in 2010. Maybe the demolition happened after the LARIAC capture? There are still bulldozers on the ground in 2014. I left one building that appears n the satellite view. 

I don't think we'll see large portions deleted again (maybe a couple north of LAX), but it was a quirk in that particular import and validation. Though, at the time of that block we didn't know that the satellite imagery was newer.

**Comment by maning** [comment]
Awesome @jschleuss, closing as this is fixed.
