### ISSUE TITLE
Diary posts on our progress

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#91]
Per convo at gitter, we will line up a series of OpenStreetMap diaries.  Intent is to:
- update the community on the progress of this import,
- share what we built to do execute the import (tools, processes, etc)
- invite the community to participate

Here's a couple of ideas, we can divide them into a series of posts for each of us to work on:
- [ ] Status of the import (stats, events, etc);
- [x] Quality of data we are importing (not just building shapes but also height, year built, building types, etc);
- [x] Tools we built (data conversion, tagging, Tasking Manager customizations, JOSM plugin); @maning
- [x] Working with the community (mapathons, coordination with LA City planning office). @jschleuss 

At the end of the posts, lets invite the community to join in the effort and see us [present at the SOTM-US](http://stateofthemap.us/2016/lets-get-la-on-the-map/) next month.

More ideas?

@almccon @jschleuss @cityhubla

**Comment by jschleuss** [comment]
This sounds great to me. I can take the community angle.

**Comment by maning** [comment]
Tools diary post: https://www.openstreetmap.org/user/manings/diary/38969

**Comment by maning** [comment]
Data quality post: http://www.openstreetmap.org/user/manings/diary/39081

**Comment by jschleuss** [comment]
Community post: https://www.openstreetmap.org/user/schleuss/diary/39161

Will do another one with the government help/communication.

**Comment by jschleuss** [comment]
Also posted this https://www.openstreetmap.org/user/schleuss/diary/39136

which is related

**Comment by maning** [comment]
All done here. Closing.
