### ISSUE TITLE
Additional tags for buildings

### ISSUE THREAD

**Issue by jschleuss** [osmlab/labuildings#95]
I'd like to make these adjustments to the tags, based on an email sent forever ago by [Steve All](https://www.openstreetmap.org/user/stevea), who sent along some handy suggestions. I've finally reviewed the data and think we can use the top portion after some discussion. I've left my notes on not importing the group in the bottom section.

This one is mine that I've noticed in large buildings being called building=house and building:units=1. It's because the building sits on several "stacked" parcels for each individual condominium (an owned apartment in a larger building).

We'd need to scrub anything that is "SpecificUseDetail2" as "Condominium" to be building=residential.

The rest below are all based on the "SpecificUseDetail1" column in the [assessor file](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2015/hvzm-fn38).

# **To change:**
> Building Supplies (Home Depot, etc.)
shop=doityourself

This appears to be all do it yourself type shops, so this could work. 60 instances.

> Cemetery, Mausoleum
amenity=grave_yard, amenity=crematorium

It's not clear which ones are actually crematoriums, where bodies are burned. But I think amenity=grave_yard would work. 331 parcels.

> Convalescent Hospital, Nursing Home
amenity=social_facility
social_facility=assisted_living
social_facility=day_care

All of these have a SpecificUseType of "Hospital." I suppose we could add these other tags. 136 instances.

> "Hotel - 50 Rooms and Over" and "Hotel - Under 50 Rooms"
tourism=hotel

Good add. 1,060 instances.

> Legitimate (Stage) Theater
amenity=theatre

Good add. 51 instances.

> "Motel - 50 Rooms and Over" and "Motel - Under 50 Rooms"
tourism=motel

Good add. 1,085 instances.

> Parking Structures - Commercial Parking	
amenity=parking

Appears to be accurate, based on county's satellite in assessor map. 94 instances.

> Parking Structures - Patron or Employee	
amenity=parking
access=private

Also appears in county satellite imagery. 206 instances.

> Petroleum Refinery						
man_made=works
product=petroleum

Seems to work. There are a lot of man_made=storage_tank on these properties, which we've mostly corrected for. 109 properties.

> Single Residence
building=house

These are manufactured homes. Should be building=house
1,702 parcels.

> Small Food Store
shop=convenience

This works. 133 instances.

# **Not worth changing:**
> Beverage
shop=beverage

These are all industrial food processing plants and will get building=industrial

> Church Parking Lot
amenity=parking

There are several of these descriptions, but they describe the entire property, which includes buildings (like churches or mosques) and parking lots (separate from the buildings). L.A. County recently released a [parking lot shapefile](http://egis3.lacounty.gov/dataportal/2016/01/25/parking-lot-boundaries-commercial-industrial-government-2014/) which we could use to import parking spots. 

> Discount Department Store
shop=variety_store

These are coming in already as shop=department_store based on the SpecificUseType of "Department Store."

> Fee Owned Boat Slip
leisure=slipway
fee=yes

There are only two buildings in the whole set with this. Look like errors, where the parcel boundary bisects a building (and cuts off a sliver).

> Gymnasium, Health Spa
leisure=fitness_centre

Weirdly Disney Studio's in Burbank is classified as this. All 44 buildings come over with that description. Most definitely an error in the county's data. Other parcels include LA Fitness, but have multiple buildings like Target and restaurants on that property.

> Home Furnishings
shop=furniture

These all have the SpecificUseType of "Department Store," which is a little more generic. Some of the properties have buildings with jewelry shops and other things.

> Horse Stable
leisure=horse_riding

Not all of these properties appear to be this anymore.

> Movie - Drive-in
amenity=cinema + drive_in=yes

This only affects six properties, but it's hard to verify if they're still drive-in theaters.

> Movie - Indoor
amenity=cinema

These tend to not be standalone structures and instead are part of something else, such as a nearby department store.

> Restaurant, Cocktail Lounge, Tavern
amenity=bar

Not always standard. Sometimes the building has several other non-restaurant businesses inside a strip mall.

> Supermarket
shop=supermarket

Many of these properties have multiple buildings with different uses. Like a grocery store next to a pharmacy and a furniture store.

> Trailer and Camper Park
tourism=caravan_site

Would be better as an area than a building type.

> Veterinary Hospital
amenity=veterinary

Doesn't seem to be very accurate. 

> Warehousing
building=warehouse

Should already be caught by parent Warehousing category.

> Wireless Communications Tower
man_made=tower

Towers do not appear to make it into the building file (too thin).

# **All SpecificUseDetail and count (these are just individual properties and not unique buildings)**

4 Stories or Less	245080
5 Stories or More	1260
Adult Care Facility - Social and Recreational Services	14
Adult Day Services - Skilled Care Services Offered	8
Amusement Facility	25
Artist in Residence	116
Auditorium, Stadium, Amphitheater	130
Auto Body Repair Shop	6639
Auto Service Centers (No Gasoline)	488
Beverage	29
Building Supplies (Home Depot, etc.)	60
Car Wash Only	232
Car Wash Only, Self-service Type	145
Cement, Rock and Gravel Plant	50
Cemetery, Mausoleum	331
Church Parking Lot	256
Commercial Swimming Pools, School	20
Concessions	9
Contractor Storage Yard	64
Convalescent Hospital, Nursing Home	136
Dance Hall	23
Detached	6425
Discount Department Store (Target, etc.)	87
Farm and Construction Equipment Sales and Service	27
Fast Food - Auto Oriented	439
Fast Food - Walk Up	563
Fee Owned Boat Slip	331
Full Service	1544
Government Services	465
Gymnasium, Health Spa	113
High Rise 5 Stories or More	6184
High Value Residence, X Cost Classification	463
Home Furnishings (Ethan Allen, etc.)	12
Horse Stable - Private	32
Hotel - 50 Rooms and Over	558
Hotel - Under 50 Rooms	502
Ice	56
Legitimate (Stage) Theater	51
Loft-type Buildings	134
Lots - Commercial Parking	305
Lots - Patron or Employee	13136
Meat	370
Medical Dental Building	1578
Microwave Relay Tower	17
Miniature	2
Misc. Privately Owned Properties That Do Not Fall Into Any Other Classification	88
Miscellaneous	492
Miscellaneous Commercial	616
Miscellaneous Industrial	399
Mortuary, Funeral Home	54
Motel - 50 Rooms and Over	251
Motel - Under 50 Rooms	834
Motel/Hotel and Apartment Combinations - 50 Units and Over	25
Motel/Hotel and Apartment Combinations - Under 50 Units	34
Movie - Drive-in	6
Movie - Indoor	112
Multiple Residence	7
New Car Sales and Service	372
Non Profit	11
Office and Residential	560
Other	181
Own-your-own Lot	25
Parking Structures - Commercial Parking	94
Parking Structures - Patron or Employee	206
Petroleum Refinery, Chemical Plant	109
Private Rural Pumping Plant	136
Public School	751
Public Storage (Bekins, Lyons)	44
Public Storage - Mini Warehouse	529
Recreation	467
Recreation Equipment Sales and Service (Campers, Motor Homes and Boats)	58
Restaurant, Cocktail Lounge, Tavern	4762
Retail-Warehouse Combo (Levitz, etc.)	38
Rights of Way	188
Roller	1
Self Service	327
Single Residence	1702
Small Food Store - Less than 6,000 SF	133
Store and Office Combination	3719
Store and Residential Combination	8938
Studio	302
Supermarket - 12,000 SF or More	494
Supermarket - 6,000 SF through 11,999 SF	55
Tennis Court, Club, Pro Shop	46
Three Par	21
Townhouse Format	8395
Trailer and Camper Park (Overnight)	7
Transmission Facility	31
Transportation	237
Trucking Company, Terminal	122
Used Car Sales	381
Veterinary Hospital, Clinic	156
Warehouse Store (Costco, etc.)	53
Warehousing, Distribution, 10,000 to 24,999 SF	2096
Warehousing, Distribution, 25,000 to 50,000 SF	1262
Warehousing, Distribution, Over 50,000 SF	1677
Warehousing, Distribution, Under 10,000 SF	7358
Water Related Facilities	718
Wireless Communication Tower	587
With Car Wash	133

**Comment by maning** [comment]
@jschleuss This is great! Can you edit the [csv](https://github.com/osmlab/labuildings/tree/master/mappings_csv) so I can rerun the script?

One question, what do we do with those that were already imported?

**Comment by jschleuss** [comment]
@maning Yes! I'll edit that today. I don't think it'll be that bad to update those already on the map. We can use overpass turbo or maybe make a Maproulette project out of it. I can be responsible since I took so long to look through the data and think of what actually works.

**Comment by jschleuss** [comment]
Oh, the "condominium" one will be harder because there are 18,150 unique locations. Yeah, that could be painful. Similarly could be a Maproulette project to just remove building=house and building:units=1 and replace with building=residential.

**Comment by jschleuss** [comment]
@maning I think it's good. I'm not totally sure if my edit to the osm_tags.py file were accurate. Adds two more keys and values for some of the Specific_1 items.

**Comment by maning** [comment]
This is done and ready for import.
