### ISSUE TITLE
How important is it to merge building silvers?

### ISSUE THREAD

**Issue by planemad** [osmlab/labuildings#98]
As per [current guidelines](https://github.com/osmlab/labuildings/blob/master/IMPORTING.md), we tell importers to manually fix building silvers before upload.

> Check for small building parts that should be joined to the main building. We've already found a few examples of these in the data (see issue #19), so make sure you keep an eye out for these. To join small parts, select both polygons and select Tools > Join overlapping Area.

Given that the silvers affect less than 1% of the buildings, not sure if it makes sense to spend as much as double the time it takes for conflation to merge silvers. Rather a more efficient approach might be to detect all such silvers post import and attempt to merge them as a separate project?

My suggestions is for the guideline to mention that merging silvers is not the focus of the task, so should not be grounds to invalidate blocks.

cc @jschleuss  @maning

**Comment by jschleuss** [comment]
Great point. The slivers are a result of a lower quality property file cutting across the building file. I'm up for debate on whether or not we should focus on merging the slivers. The San Fernando Valley has been covered in those slivers and it's a great irritation.

I think they should be merged, but I don't see a reason for that to invalidate a block. Whoever is doing validation can very quickly scan the area for any areas needing to be merged.

**Comment by maning** [comment]
Import is done for LACity, we will do a [cleanup task](https://github.com/osmlab/labuildings/issues/104) to fix this.
