### ISSUE TITLE
Next steps after LA City

### ISSUE THREAD

**Issue by maning** [osmlab/labuildings#99]
This week we hit the **[1M building mark](https://taginfo.openstreetmap.org/keys/lacounty:bld_id#overview)** and close to finishing [SF Valley](http://labuildingsimport.com/project/7) (88% done) and validation for [Central/East side](http://labuildingsimport.com/project/6) (91% validated).  

![screen shot 2016-07-15 at 12 04 32](https://cloud.githubusercontent.com/assets/353700/16878606/cc2ca154-4aca-11e6-8209-4c8b791e5945.png)

Upon completion we should:
- [x] send a thank you note to all the [~100 contributors](https://github.com/osmlab/labuildings/issues/40) (I will cleanup the lists as there are probably duplicated usernames)
- [x] run a full sweep to fix data issues such as overlap, duplicates, self-intersections, wrong tags, etc. ([tickets here](https://github.com/osmlab/labuildings/issues?q=is%3Aopen+is%3Aissue+label%3Acleanup)).
- [x] share this milestone as post to mailinglists, diary, twitter.

**After LA City what's next?**

![screen shot 2016-07-15 at 19 35 29](https://cloud.githubusercontent.com/assets/353700/16878627/e2611568-4aca-11e6-9761-fdb31edfb602.png)
_[Missing buildings outside LA City](https://api.mapbox.com/styles/v1/maning/ciglqvpbj000maakn5dz2lvb8.html?title=true&access_token=pk.eyJ1IjoibWFuaW5nIiwiYSI6IlhjWGNfdTQifQ.ras0nImWG638BCDSxU8bqw#15.48/33.8101/-118.2954)_

We have 2M more buildings to import for the rest of the county, before doing that let's 
revisit our approach.
- What's the ETA on public release of the [2014 building data](http://egis3.lacounty.gov/dataportal/2014/10/16/countywide-building-outlines-2014/)?
- Review the processing scripts to [fix common geometry issues](https://github.com/osmlab/labuildings/issues?q=is%3Aissue+is%3Aopen+label%3Abug) before the actual import.
- How do we engage local community outside LA City?
- It took us ~4 months to do LA City, how can we move faster?

cc/ @almccon @jschleuss @cityhubla @planemad @lxbarth

**Comment by jschleuss** [comment]
@maning 

I agree with all of this. 

> What's the ETA on public release of the 2014 building data?

The 2014 buildings for the rest of the county will be available in October.

> Review the processing scripts to fix common geometry issues before the actual import.

The slivers of buildings have been particularly awful in the SF Valley. However, this is an LA City decision to split buildings along lower-quality property boundaries. I do not expect we will see many of those going forward. But we should check for small geometries just in case.

> How do we engage local community outside LA City?

I've started reaching out to local universities. I think that'll be a good way. More ideas welcome.

> It took us ~4 months to do LA City, how can we move faster?

The drag, I think, lies with the local movement. If we all work out a schedule I can schedule mapping events around dates to help organize and speed up the local work. 

Should we wait for the 2014 data to be released? I can reach out to the county and ask how many buildings will need to be edited if we go forward with the 2008 data. If we don't want to wait, should we split up the rest of the county?

Here are the city totals for reference:

| city             | total_buildings | note                                                         |
|------------------|-----------------|--------------------------------------------------------------|
| LOS ANGELES      | 1,090,136       |                                                              |
| unincorporated   | 356,860         |                                                              |
| LONG BEACH       | 137,060         |                                                              |
| PASADENA         | 113,821         | excluded                                                     |
| GLENDALE         | 55,904          |                                                              |
| SANTA CLARITA    | 54,136          |                                                              |
| LANCASTER        | 49,771          |                                                              |
| TORRANCE         | 48,269          |                                                              |
| PALMDALE         | 45,812          |                                                              |
| POMONA           | 41,133          |                                                              |
| BURBANK          | 37,844          |                                                              |
| LAKEWOOD         | 36,457          |                                                              |
| DOWNEY           | 34,346          |                                                              |
| WHITTIER         | 33,244          |                                                              |
| WEST COVINA      | 31,624          |                                                              |
| COMPTON          | 30,331          |                                                              |
| NORWALK          | 29,608          |                                                              |
| CARSON           | 29,388          |                                                              |
| INGLEWOOD        | 29,321          |                                                              |
| EL MONTE         | 28,215          |                                                              |
| SOUTH GATE       | 27,605          |                                                              |
| ALHAMBRA         | 27,133          |                                                              |
| SANTA MONICA     | 23,585          | partially done will need conflation                   |
| BELLFLOWER       | 21,473          |                                                              |
| REDONDO BEACH    | 21,426          |                                                              |
| PICO RIVERA      | 20,373          |                                                              |
| GLENDORA         | 19,987          |                                                              |
| ARCADIA          | 19,474          |                                                              |
| BALDWIN PARK     | 18,972          |                                                              |
| MONTEREY PARK    | 18,936          |                                                              |
| GARDENA          | 18,547          |                                                              |
| MONTEBELLO       | 18,067          |                                                              |
| LYNWOOD          | 17,689          |                                                              |
| HAWTHORNE        | 17,516          |                                                              |
| ROSEMEAD         | 17,126          |                                                              |
| COVINA           | 15,758          |                                                              |
| DIAMOND BAR      | 15,714          |                                                              |
| LA MIRADA        | 15,485          |                                                              |
| RANCHO PALOS VER | 15,483          |                                                              |
| TEMPLE CITY      | 15,311          |                                                              |
| CERRITOS         | 15,126          |                                                              |
| MANHATTAN BEACH  | 14,837          |                                                              |
| CULVER CITY      | 14,650          |                                                              |
| MONROVIA         | 14,481          |                                                              |
| SAN GABRIEL      | 13,832          |                                                              |
| BEVERLY HILLS    | 12,507          | will need conflation                             |
| PARAMOUNT        | 12,226          |                                                              |
| SAN DIMAS        | 12,164          |                                                              |
| CLAREMONT        | 12,143          |                                                              |
| AZUSA            | 12,084          |                                                              |
| LA VERNE         | 11,849          |                                                              |
| HUNTINGTON PARK  | 11,764          |                                                              |
| LA CANADA-FLINTR | 9,788           |                                                              |
| WALNUT           | 9,372           |                                                              |
| SOUTH PASADENA   | 9,085           |                                                              |
| BELL GARDENS     | 9,053           |                                                              |
| LAWNDALE         | 8,991           |                                                              |
| LA PUENTE        | 8,851           |                                                              |
| SAN FERNANDO     | 8,493           |                                                              |
| SAN MARINO       | 8,006           |                                                              |
| SANTA FE SPRINGS | 7,991           |                                                              |
| BELL             | 7,865           |                                                              |
| LOMITA           | 7,545           |                                                              |
| CALABASAS        | 7,511           |                                                              |
| MALIBU           | 7,421           |                                                              |
| EL SEGUNDO       | 7,281           |                                                              |
| SOUTH EL MONTE   | 7,128           |                                                              |
| HERMOSA BEACH    | 6,906           |                                                              |
| DUARTE           | 6,655           |                                                              |
| AGOURA HILLS     | 6,596           |                                                              |
| PALOS VERDES EST | 6,424           |                                                              |
| WEST HOLLYWOOD   | 6,381           | some of these are already done                               |
| MAYWOOD          | 5,988           |                                                              |
| SIERRA MADRE     | 5,370           |                                                              |
| COMMERCE         | 5,314           |                                                              |
| ARTESIA          | 5,269           |                                                              |
| CUDAHY           | 4,294           |                                                              |
| ROLLING HILLS ES | 3,901           |                                                              |
| SIGNAL HILL      | 3,466           |                                                              |
| HAWAIIAN GARDENS | 3,179           |                                                              |
| WEST LAKE VILLAG | 3,026           |                                                              |
| LA HABRA HEIGHTS | 2,998           |                                                              |
| INDUSTRY         | 1,858           |                                                              |
| VERNON           | 1,683           | done (exists as one block group touching LA City boundaries) |
| ROLLING HILLS    | 1,626           |                                                              |
| IRWINDALE        | 1,590           |                                                              |
| AVALON           | 1,108           |                                                              |
| HIDDEN HILLS     | 1,063           |                                                              |
| BRADBURY         | 693             |                                                              |

**Comment by jschleuss** [comment]
I think of our biggest decisions is to decide whether or not to wait for the 2014 L.A. County buildings file. 

Here's are some numbers to help us decide.

According to the recently released [2016 assessor file](https://data.lacounty.gov/Parcel-/Assessor-Parcels-Data-2016/7rjj-f2pv) there are about 1.5 million pre-2008 buildings outside of the city of Los Angeles. Since the beginning of 2008 more than 30,000 buildings have been added to areas outside of L.A. City. About 3,000 were built since 2014, so they likely wouldn't show in the file anyway.

What that means is if we import the 2008 county data we will likely have to add 27,000 buildings after the October release of the 2014 data. I'm not sure if that's a high or a low number, but we could task it out over a few months and handle it locally.

![la-g-la-county-buildings-built-since-jan-2008-2016-08-18-chartbuilder-3](https://cloud.githubusercontent.com/assets/695934/17785414/777ac584-6535-11e6-8bfc-4b66dfa38f68.png)

**Comment by maning** [comment]
Capturing skype convo with @maning @cityhubla @jschleuss  today.

**We will proceed with importing the current data we have**.  Once 2014 is released, we will review how to conflate the ~197K modified/new/replacement.  

![screen shot 2016-08-20 at 17 17 46](https://cloud.githubusercontent.com/assets/353700/17831007/9c21f836-66fb-11e6-86c4-23cbe6f55fa4.png)<br>_Breakdown of building status in the 2014 data_

Import activities will continue to revolve around MaptimeLA events and other activities around the county. Mapbox team will support import and validation.

**Next steps**
- [x] prepare the geojson files for TM project.  Review the block coverage to ensure no overlaps exist between the already imported blocks @maning
- [x] create TM projects for South bay and Harbor @jschleuss 
- [x] promote cleanup tasks to the community (i.e. split buildings, retagging garages, etc.) @cityhubla @jschleuss 
- [x] review and implement a way to split tasks to comply with upcoming 10K upload limit per changeset in the OSM API (https://github.com/osmlab/labuildings/issues/106) @maning @batpad

**Comment by maning** [comment]
We are now using 2016 released buildings. Closing.
